cartesi/machine-emulator

.github/workflows/Dockerfile, .github/workflows/build.yml, CHANGELOG.md, src/.gitignore, src/Makefile, src/cartesi-machine.lua, src/clua-cartesi.cpp, src/machine-c-defines.h, src/riscv-constants.h, tools/template/machine-c-version.h.template
This PR introduces two new command line options:
- `--version` to be used by users, so they can known what current cartesi machine version is installed
- `--version-json` to be used by tools, so they can retrieve version and some other details about the current cartesi machine installed
This is the output for both commands:
```
$ cartesi-machine --version
cartesi-machine 0.14.0
git commit: 3b11d5e07dc650a1b4c443a8232bc8b2ebd9d363
build time: Jun  7 2023 19:19:03
platform: linux
compiler: GNU C++ version 13.1.1 20230429
Copyright 2019-2023 Cartesi Pte. Ltd.
$ cartesi-machine --version-json
{
  "version": "0.14.0",
  "version_major": 0,
  "version_minor": 14,
  "version_patch": 0,
  "version_label": "",
  "marchid": 15,
  "mimpid": 14000,
  "default_rom_image": …
```
=> Add `--version` to cartesi-machine

src/jsonrpc-remote-machine.cpp, src/remote-machine.cpp
The JSONRPC remote cartesi machine server was missing log-level control.
This PR adds this control, both by means of an environment variable `REMOTE_CARTESI_MACHINE_LOG_LEVEL`, or with a command-line option `--log-level` (which takes precedence). It therefore closes #71.
It also adds SIGTTOU handling, which was missing.
=> Add log level and SIGTTOU control to JSONRPC remote cartesi machine server

CHANGELOG.md, src/cartesi-machine.lua, src/clua-machine-util.cpp, src/htif-factory.cpp, src/htif-factory.h, src/htif.cpp, src/json-util.cpp, src/json-util.h, src/jsonrpc-discover.json, src/machine-c-api.cpp, src/machine-c-api.h, src/machine-runtime-config.h, src/machine.cpp, src/machine.h
This issue implements #72
Using the new `--skip-root-hash-check` option we can run a test suite without the merkle tree root hash checking every machine load, saving several seconds when running dapp test suites. I am using this feature with JSONRPC to speed up Lua unit tests I am creating.
Using the new `--skip-version-check` option we can test old snapshots created by Sunodo. Ideally we should not run snapshots targeting old emulator releases, but for development users like us, who need to test stuff before they are actually released, this check is a pain, because it prevents us from testing old snapshots created by Sunodo with emulators in development.
Using the new `--htif-no-console-putchar` option we can suppress anything written to machine's stdout/stderr. This is useful when …
=> Add runtime options to skip root hash, version check and suppress putchar

src/shadow-tlb.h
We only provide abs_addr currently and rel_addr is useful for zk-arch
=> feat: add tlb_get_entry_hot/cold_rel_addr

.github/workflows/build.yml, CHANGELOG.md, Makefile, src/Makefile, src/cartesi-machine-stored-hash.lua, src/cartesi-machine-tests.lua, src/cartesi-machine.lua, src/cartesi/gdbstub.lua, src/cartesi/proof.lua, src/cartesi/util.lua, src/rollup-memory-range.lua, src/tests/htif-console.lua, src/tests/htif-rollup.lua, src/tests/htif-yield.lua, src/tests/log-with-mtime-transition.lua, src/tests/machine-bind.lua, src/tests/machine-test.lua, src/tests/mcycle-overflow.lua, src/tests/mtime-interrupt.lua, src/tests/test-jsonrpc-fork.lua, src/tests/util.lua, src/uarch-riscv-tests.lua, third-party/riscv-arch-tests/src/run-rv64i-arch-test.lua, tools/benchmarks/run-benchmarks.lua
- Adds static analysis for Lua code in target `make check-lua` and CI using [Luacheck](https://github.com/lunarmodules/luacheck)
- Adds code formatting check for Lua code in target `make check-format-lua` and CI using [StyLua](https://github.com/JohnnyMorganz/StyLua). Lua code can also be formatted using `make format-lua`.
- Fixes all warnings raised by Luacheck.
- Formats all Lua code.
I tried to choose a Lua style format configuration that would approximate the current Lua style we use.
- https://github.com/cartesi/machine-emulator/pull/33
*This PR depends on the above PRs, they should be reviewed first.*
=> Add static analysis and formatting for Lua code

CHANGELOG.md, src/cartesi-machine.lua, src/clua-i-virtual-machine.cpp, src/clua-machine-util.cpp, src/clua.h, src/machine.cpp, src/test-machine-c-api.cpp, src/tests/htif-console.lua, src/tests/htif-rollup.lua, src/tests/htif-yield.lua, src/tests/log-with-mtime-transition.lua, src/tests/machine-test.lua, src/tests/mcycle-overflow.lua, src/tests/mtime-interrupt.lua, src/tests/util.lua, src/uarch-riscv-tests.lua, tools/benchmarks/run-benchmarks.lua
This implements #42 and #69 
Both issue allow us to simplify some Lua tests.
- https://github.com/cartesi/machine-emulator/pull/35
- https://github.com/cartesi/machine-emulator/pull/33
*This PR depends on the above PRs, they should be reviewed first.*
=> Add support for to-be-closed variables for machine Lua API

src/jsonrpc-discover.json
https://github.com/open-rpc/generator (generates typescript, rust bindings)
needs "title" to be accurate in order to not construct badly named types
Effect:
```
+++ client/rust/src/index.rs    2023-06-21 09:02:27.583333451 +0200
@@ -8,90 +8,91 @@
use serde::{Serialize, Deserialize};
use derive_builder::Builder;
-pub type Integer7Bd9WOt2 = i64;
-pub type UnorderedSetOfInteger7Bd9WOt2MMEUfR9Y = Vec<Integer7Bd9WOt2>;
+pub type UnsignedInteger = i64;
+pub type XRegConfig = Vec<UnsignedInteger>;
+pub type FRegConfig = Vec<UnsignedInteger>;
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Builder, Default)]
#[builder(setter(strip_option), default)]
#[serde(default)]
-pub struct ObjectOfUnorderedSetOfInteger7Bd9WOt2MMEUfR9YInteger7Bd9WOt2Integer7Bd9WOt2Integer7Bd9WOt2Integer7Bd9WOt2Integ …
```
=> Add titles to components in JSONRPC in order to let OpenRPC stub generators make nicer stubs

.github/workflows/build.yml, src/machine.cpp, src/machine.h, src/tests/machine-bind.lua, src/tests/util.lua, src/uarch-record-state-access.h, src/uarch-riscv-tests.lua
This branch adds the option to include proofs in the json log files produced by uarch-riscv-tests.lua.
The logged proofs will be used as test fixture by the Solidity step.
This PR also includes a fix to a bug that was found while testing the new option `--proofs-frequency=<number>`.
This bug occurs when proofs are not requesdted, leaving the merkle tree inconsistent because updated pmas are not marked dirty, causing the following exception:
```
merkle tree must be consistent when stepping alternating with and without proofs...
lua5.4: tests/machine-bind.lua:809: inconsistent merkle tree
stack traceback:
[C]: in method 'step_uarch'
tests/machine-bind.lua:809: in local 'f'
```
=> Add proofs to uarch riscv tests

.github/workflows/build.yml
Generate proofs for all accesses in uarch-riscv-tests-json-logs
=> ci: Add all proofs to uarch-riscv-tests-json-logs

src/test-utils.h
The`PAGE_SIZE` constant in `test-utils.h` was declared in the global namespace was colliding with the same identifier declared by `vm_param.h` when compiling on a Mac. This PR moves the constant to the `detail` namespace so it is kept separate.
=> fix: move constants to namespace to avoid colision

.github/workflows/build.yml, Dockerfile, src/cartesi-machine-tests.lua, src/cartesi-machine.lua, src/machine-config.h, src/machine.cpp, src/tests/htif-rollup.lua
=> Rollup enable by default

Dockerfile, README.md, src/Makefile, src/json-util.h, src/jsonrpc-remote-machine.cpp, src/jsonrpc-virtual-machine.cpp, src/test-machine-c-api.cpp, third-party/dependencies, third-party/shasumfile
This is to simplify our dependencies, so the cartesi machine is easier to build on more platforms.
I could copy the single file to our repository, but I choose to download it instead, to avoid license issues.
=> refactor: bundle nlohmann-json into third-party

src/json-util.cpp
Some recent commit has indirectly caused `INT_MAX` not to be defined in `json-util.cpp` and it fails to compile under `g++ (Ubuntu 12.3.0-1ubuntu1~23.04) 12.3.0`. This PR includes `<climits>` to fix the problem.
=> fix: missing climits include in json-util.cpp

src/cartesi-machine.lua
Fix for https://github.com/cartesi/machine-emulator/issues/162
=> fix: make append options work when empty

src/tests/machine-bind.lua
In unit test, use pattern matching instead of hard-coded hashes when testing uarch reset log.
=> chore: Use pattern to test reset log

src/uarch-reset-state-access.h, tests/lua/machine-bind.lua
This branch fixes a bug where PMA pages are not marked dirty by uarch_reset() creating inconsistent root hash.
=> fix: Pages not marked dirty after uarch reset

src/jsonrpc-discover.json
Pasting the content into https://playground.open-rpc.org/ makes it complain about this issue.
=> Fix trailing comma in jsonrpc-discover.json

src/cartesi-machine.lua
Currently the machine is using Sv57 virtual memory address spacing (5 level), however nodejs does not work with Sv57, furthermore address translation with a 5 level has more overhead on TLB misses than Sv39 which only has 3 levels.
I checked there is only two ways to force using Sv39 in recent kernel:
1. Add `no4lvl` to bootargs
2. Disable Sv48 and Sv57 modes in `satp` CSR.
While option 2. would be optimal in terms of performance, I decided to go for 1. in case a dapp wants to remove `no4lvl` from bootargs to map more 512GB to virtual memory.
Looks like `mmu-type: riscv,sv39` in DTB is ignored in recent kernels, but I left the entry there to keep supporting old kernels.
=> Use Sv39 address spacing by default to support nodejs and improve performance

src/cartesi-machine.lua
This makes easier to test the cartesi machine as root, useful you are prototyping with virtio network and want to install packages. Also refactors how the default user is chosen, this is now set by tools init script (this is more appropriate since the user existence depends on it).
```sh
$ cartesi-machine --user=root id 
.
/ \
/    \
\---/---\  /----\
\       X       \
\----/  \---/---\
\    / CARTESI
\ /   MACHINE
'
uid=0(root) gid=0(root) groups=0(root)
Halted
```
```sh
$ cartesi-machine id 
.
/ \
/    \
\---/---\  /----\
\       X       \
\----/  \---/---\
\    / CARTESI
\ /   MACHINE
'
uid=1000(dapp) gid=1000(dapp) groups=1000(dapp)
```
- https://github.com/cartesi/machine-emulator-tools/pull/39
=> feat: introduce the `--user` command line option

src/cartesi-machine.lua, src/clua-machine-util.cpp, src/json-util.cpp, src/jsonrpc-discover.json, src/machine-c-api.cpp, src/machine-c-api.h, src/machine-runtime-config.h, src/machine.cpp
I needed this feature to speed up development/testing until we have a faster way to save/load merkle tree root hashes without doing whole computation all the time, it should not be used in production, it is complementary to the `--skip-root-hash-check` runtime option.
This is also useful when saving snapshots in WASM environment, machine root hash computation takes forever there, and storing machine snapshots in WASM is useful to save the state of the machine locally to later be resumed.
=> feat: add new runtime option to skip storing machine root hash

src/cartesi-machine.lua
This PR introduces `--env`, `--workdir` and `--hostname` Docker like options for convenience.
For instance you execute the following now:
```
cartesi-machine \
--hostname=test-cm \
--user=root  \
--volume=.:/mnt \
--workdir=/mnt \
--env=VAR=1 \
-it bash
Running in unreproducible mode!
.
/ \
/    \
\---/---\  /----\
\       X       \
\----/  \---/---\
\    / CARTESI
\ /   MACHINE
'
root@test-cm:/mnt# env | grep VAR
VAR=1
root@test-cm:/mnt#
```
Looking more similar to `docker run` usage.
=> Add new docker like command line options

.github/workflows/build.yml
This should make the step "Run test suite with microarchitecture and host based interpreters comparing machine hashes at every step" about ~20 minutes faster.
Before this change, 8 tests were being executed in parallel, each one with 8 threads for root hash computation, making the machine use 64 threads on a 8 core machine, not ideal. With this change only 8 threads will be working, speeding up the CI a little.
=> ci: speed up uarch testing in CI

src/clua-i-virtual-machine.cpp, src/i-virtual-machine.h, src/jsonrpc-discover.json, src/jsonrpc-remote-machine.cpp, src/jsonrpc-virtual-machine.cpp, src/jsonrpc-virtual-machine.h, src/machine-c-api.cpp, src/machine-c-api.h, src/machine.cpp, src/machine.h, src/virtual-machine.cpp, src/virtual-machine.h, tests/misc/test-machine-c-api.cpp
This PR adds a new function to the public C API:
1. `cm_translate_virtual_address` - Translates a virtual memory address to its corresponding physical memory address
The use case is to debug address translation from outside, this function was exposed to Lua and JSONRPC.
=> feat: add C API to translate virtual address

src/jsonrpc-virtual-machine.cpp
Limits the SO_LINGER workaround to macOS only.
=> fix: Limit SO_LINGER workaround to macOS

src/uarch-step.cpp, tests/lua/uarch-riscv-tests.lua
- Simplify generation of Solidity files
- Remove `dumpIns`
- Remove unused arguments
- Add specific fields in catalog.json to distinguish between binary and log files
=> Simplify solidity step generation

src/cartesi-machine.lua, src/clua-i-virtual-machine.cpp, src/clua-jsonrpc-machine.cpp, src/i-virtual-machine.h, src/jsonrpc-discover.json, src/jsonrpc-machine-c-api.cpp, src/jsonrpc-machine-c-api.h, src/jsonrpc-mg-mgr.h, src/jsonrpc-remote-machine.cpp, src/jsonrpc-virtual-machine.cpp, src/jsonrpc-virtual-machine.h, src/machine-c-api.cpp, src/machine-c-api.h, src/virtual-machine.cpp, src/virtual-machine.h
This is a fix for https://github.com/cartesi/machine-emulator/issues/202 and also adds new command line options `--no-rollback` that fulfills https://github.com/cartesi/machine-emulator/issues/206
=> Rework machine snapshots API

src/jsonrpc-remote-machine.cpp, src/jsonrpc-virtual-machine.cpp
This will fix hard to happen problems when:
- Doing `shutdown()` followed by a `rebind()` with JSON-RPC.
- Connection TIME_WAIT accumulation when doing thousands of snapshots per second.
=> Fix JSONRPC connection issues on edge cases

src/virtual-machine.cpp
This will allows saving local machine snapshots on first yield. This usually worked without any special cli flag, but in the last release only works with `--no-rollback`, this PR make it work as before again.
=> fix: allow saving snapshots on first machine yield

.gitignore, Dockerfile, Makefile, README.md, src/Makefile, src/asio-config.h, src/clua-jsonrpc-machine.cpp, src/json-util.h, src/jsonrpc-machine-c-api.cpp, src/jsonrpc-machine-c-api.h, src/jsonrpc-mgr.h, src/jsonrpc-remote-machine.cpp, src/jsonrpc-virtual-machine.cpp, src/jsonrpc-virtual-machine.h, tests/lua/test-jsonrpc-fork.lua, tests/misc/Makefile, third-party/dependencies, third-party/nlohmann-json/LICENSE.MIT, third-party/nlohmann-json/json.hpp, third-party/shasumfile
Implementation details:
- The client uses synchronous IO.
- In the client, special care is taken when connect/write/read calls are interrupted, so the client does not lose track of spawned remote machines, otherwise it could leave dead zombies when its process receives SIGTERM/SIGINT.
- The client persist connections with keep alive, so we speed up request throughput
- The client still use SO_LINGER option to minimize TIME_WAIT connections during fork
- Both client and server uses TCP_NODELAY to minimize connection latency
- The server uses asynchronous IO, so we can supporting connecting multiple clients in parallel and forking them.
- The server only shut downs when all asynchronous operations are either completed or cancelled. Meaning SIGTERM will not make it close right-away, it will …
=> Replace mongoose with Boost ASIO and support keep alive connections

src/machine-config.cpp, src/machine.cpp, tests/misc/test-machine-c-api.cpp
We had a problem in production inside a cloud where saving snapshot failed due to `mkdir` failing, I think the disk was corrupt or something, we couldn't know the reason because `mkdir` is not showing the failure reason and we could not reproduce again. This PR improves the `mkdir` error with more context, so when it happens again we will know the reason.
=> fix: show system error when mkdir fails

src/Makefile, src/access-log.h, src/cartesi/util.lua, src/clua-cartesi.cpp, src/clua-machine-util.cpp, src/json-util.cpp, src/machine-c-defines.h, src/machine-merkle-tree.h, src/record-state-access.h, src/replay-state-access.h, src/send-cmio-response.cpp, src/uarch-record-state-access.h, src/uarch-replay-state-access.h, tests/lua/cartesi/tests/util.lua, tests/lua/machine-bind.lua, tests/lua/mcycle-overflow.lua, tests/lua/uarch-riscv-tests.lua, tests/misc/test-machine-c-api.cpp, tests/misc/test-utils.h
This branch increases the merkle tree leaf size to 32 bytes.
We are still able to log accesses to data smaller than 32 bytes. We log the entire 32-byte leaf where the smaller data is located.
https://github.com/cartesi/machine-solidity-step/pull/68
=> Increase word log2 size

.github/workflows/build.yml, Dockerfile, Makefile, README.md, src/Makefile, tests/Dockerfile, tests/Makefile
This PR switch the default compilation from release with asserts enabled for everything, to release with debug information with asserts disabled only for `interpret.cpp`. This makes sure people will compile an efficient emulator with just `make` when packaging by default, not requiring the use of `make relwithdebinfo=yes` or `make release=yes` anymore when packaging.
The default make is chosen to contain debug information because some distros may want to strip and move the debug information into a second debug package (for example ArchLinux does this).
Change were mades in CI to always test with debug information, except for tagged releases.
**IMPORTANT:** After this PR, if you want to compile with asserts for `interpret.cpp`, please compile with `make debug=yes`, this is something only …
=> chore: compile in release mode with debug info by default

CHANGELOG.md, src/cartesi-machine.lua, src/machine.cpp
I found out while investigating why a "reader node" using the CLI was too slow, that `--store` is always requesting a root hash computation when saving a snapshot, despite not using it, making the store operation slow, and this PR fixes the issue.
=> fix: avoid extra root hash computation when storing an image snapshot

src/jsonrpc-virtual-machine.cpp
`sigaction` is not supported on Windows, so it was not compiling
=> fix: fix compile error of libcartesi_jsonrpc on Windows

.clang-tidy, .gitignore, .typos.toml, CONTRIBUTING.md, src/base64.cpp, src/cartesi-machine.lua, src/cartesi/gdbstub.lua, src/cartesi/util.lua, src/complete-merkle-tree.cpp, src/jsonrpc-discover.json, src/jsonrpc-machine-c-api.h, src/jsonrpc-remote-machine.cpp, src/machine-c-api.h, src/machine.h, src/merkle-tree-proof.h, src/record-state-access.h, src/uarch-record-state-access.h, tests/lua/cartesi-machine-tests.lua, tests/lua/cartesi/tests/util.lua, tests/lua/htif-cmio.lua, tests/lua/machine-bind.lua, tests/lua/machine-test.lua, tests/lua/mtime-interrupt.lua, tests/lua/run-rv64i-arch-test.lua, tests/lua/uarch-riscv-tests.lua, tests/machine/CONTRIBUTING.md, tests/machine/src/htif_util.h, tests/uarch/CONTRIBUTING.md
I have been experimenting a new IDE to code, where I have enabled the following LSPs:
- typos
- clangd
- lua-language-server
This commit fix all warnings I had with them. Plus you will be able to check for typos across the code base by running `typos` command (if you have it installed in your system).
=> Fix typos across the codebase

src/clua-cartesi.cpp, src/clua-i-virtual-machine.cpp, src/machine-c-api.cpp, src/machine-c-api.h
To avoid confusion, this PR splits the functionality of `cm_new`, which creates a new local machine object from scratch, and `cm_clone_empty`, which creates a new empty object from the same type as an existing one (local or remote).
=> Split cm_new and cm_clone_empty

CHANGELOG.md, Dockerfile, LICENSES.md, Makefile, README.md, src/Makefile, src/jsonrpc-discover.json, src/machine-c-api.h, src/os-features.h, src/os.cpp, src/state-access.h, tests/Makefile, tests/dependencies, tests/dependencies.sha256, tests/lua/create-machines.lua, tools/template/tests-data-copyright.template
This PR prepares the emulator for v0.19 release and revamps the README, providing better explanation of what Cartesi Machine is, its features, link to resources, how to install it with packages, show related projects, and more.
=> prepare v0.19 for release
